// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: hello.protoc

package pbfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Helloreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mes string `protobuf:"bytes,1,opt,name=mes,proto3" json:"mes,omitempty"`
}

func (x *Helloreq) Reset() {
	*x = Helloreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_protoc_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Helloreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Helloreq) ProtoMessage() {}

func (x *Helloreq) ProtoReflect() protoreflect.Message {
	mi := &file_hello_protoc_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Helloreq.ProtoReflect.Descriptor instead.
func (*Helloreq) Descriptor() ([]byte, []int) {
	return file_hello_protoc_rawDescGZIP(), []int{0}
}

func (x *Helloreq) GetMes() string {
	if x != nil {
		return x.Mes
	}
	return ""
}

type Hellores struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *Hellores) Reset() {
	*x = Hellores{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_protoc_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hellores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hellores) ProtoMessage() {}

func (x *Hellores) ProtoReflect() protoreflect.Message {
	mi := &file_hello_protoc_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hellores.ProtoReflect.Descriptor instead.
func (*Hellores) Descriptor() ([]byte, []int) {
	return file_hello_protoc_rawDescGZIP(), []int{1}
}

func (x *Hellores) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_hello_protoc protoreflect.FileDescriptor

var file_hello_protoc_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x12, 0x06,
	0x70, 0x62, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x72,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x08, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x37, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x2e, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x10, 0x2e, 0x70, 0x62,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x70, 0x62, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x65, 0x73, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x62, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_hello_protoc_rawDescOnce sync.Once
	file_hello_protoc_rawDescData = file_hello_protoc_rawDesc
)

func file_hello_protoc_rawDescGZIP() []byte {
	file_hello_protoc_rawDescOnce.Do(func() {
		file_hello_protoc_rawDescData = protoimpl.X.CompressGZIP(file_hello_protoc_rawDescData)
	})
	return file_hello_protoc_rawDescData
}

var file_hello_protoc_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_protoc_goTypes = []interface{}{
	(*Helloreq)(nil), // 0: pbfile.helloreq
	(*Hellores)(nil), // 1: pbfile.hellores
}
var file_hello_protoc_depIdxs = []int32{
	0, // 0: pbfile.Hello.SayHello:input_type -> pbfile.helloreq
	1, // 1: pbfile.Hello.SayHello:output_type -> pbfile.hellores
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_protoc_init() }
func file_hello_protoc_init() {
	if File_hello_protoc != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hello_protoc_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Helloreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_protoc_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hellores); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_protoc_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_protoc_goTypes,
		DependencyIndexes: file_hello_protoc_depIdxs,
		MessageInfos:      file_hello_protoc_msgTypes,
	}.Build()
	File_hello_protoc = out.File
	file_hello_protoc_rawDesc = nil
	file_hello_protoc_goTypes = nil
	file_hello_protoc_depIdxs = nil
}
